EPISODES = {}

def ep(num, title, tag, chapters, scenes):
    EPISODES[num] = {"num": num, "title": title, "tag": tag, "chapters": chapters, "scenes": scenes}

TAG = "Building an AI Employee · Ep {}"

# ---------------------------------------------------------------- Episode 1
ep(1, "Chatbot vs. Agent", TAG.format(1),
   [{"name": "The difference", "from": 1, "to": 1}, {"name": "Limit of chat", "from": 2, "to": 2},
    {"name": "Tools and code", "from": 3, "to": 4}, {"name": "Hand off", "from": 5, "to": 5},
    {"name": "Under the hood", "from": 6, "to": 6}],
   [
    {"head": None, "layout": "title",
     "data": {"eyebrow": "Building an AI Employee · Episode 1", "title": "Chatbot vs. Agent",
              "sub": "A chatbot tells you what to do. An agent does it."},
     "lines": [{"say": "Episode one. Chatbot versus agent.", "show": ["g0"]},
               {"say": "A chatbot tells you what to do. An agent does it.", "show": ["g1"]}]},
    {"head": ["The difference", "Advice vs. action"], "layout": "compare",
     "data": {"left": {"title": "Chatbot", "sub": "You ask. It answers in text.",
                       "items": ["Here are 5 tips for following up with quiet leads…",
                                 "Step 1: open your CRM and filter by last reply…",
                                 "Step 2: write a friendly, short message…"]},
              "right": {"title": "Agent", "sub": "You ask. It does the work.", "accent": True, "mode": "check",
                        "items": ["Opened leads.csv", "Found 23 quiet leads", "Drafted 23 follow-ups",
                                  "Saved them to outputs/ for review"], "gap": 110}},
     "lines": [{"say": "Ask a chatbot to follow up with your quiet leads.", "show": ["L", "L0"]},
               {"say": "You get a list of tips, and you still do all the work.", "show": ["L1", "L2"]},
               {"say": "Ask an agent, and it opens the lead sheet itself.", "show": ["R", "R0"]},
               {"say": "It finds the twenty-three people who went quiet,", "show": ["R1"]},
               {"say": "drafts a follow-up for each, and saves them for you to review.", "show": ["R2", "R3"]}]},
    {"head": ["Phase 1", "See the limit of chat"], "layout": "hub",
     "data": {"center": "Chatbot", "blocked": True,
              "nodes": [{"label": "Your files"}, {"label": "Inbox"}, {"label": "CRM"}, {"label": "Calendar"}]},
     "lines": [{"say": "Phase one. See the limit of chat.", "show": ["C"]},
               {"say": "A chatbot only produces text in a window.", "show": []},
               {"say": "It can't open your files, check your inbox, or update a record.", "show": ["N0", "N1", "N2", "N3"]},
               {"say": "So you end up being the one who does the work it describes.", "show": []}]},
    {"head": ["Phase 2", "Add tools"], "layout": "hub",
     "data": {"center": "Agent", "centerSub": "SAME MODEL",
              "nodes": [{"label": "Your files", "edge": "read"}, {"label": "Inbox", "edge": "MCP"},
                        {"label": "CRM", "edge": "API"}, {"label": "Calendar", "edge": "MCP"}]},
     "lines": [{"say": "Phase two. Add tools.", "show": ["C"]},
               {"say": "An agent is the same kind of model, with tools attached, and permission to use them.", "show": ["N0", "N1"]},
               {"say": "Now it can read your files, check the inbox, and update records itself.", "show": ["N2", "N3"]}]},
    {"head": ["Phase 2", "Let it run code"], "layout": "terminal",
     "data": {"lines": [["dim", "# leads with no reply in 5+ days"],
                        ["code", 'leads = read_csv("leads.csv")'],
                        ["code", "quiet = [l for l in leads if l.days >= 5]"],
                        ["code", "print(len(quiet))"],
                        ["out", "23"]],
              "side": {"title": "Result", "rows": [{"t": "23", "big": True, "accent": True},
                                                    {"t": ""}, {"t": "quiet leads,"}, {"t": "counted exactly"}]}},
     "lines": [{"say": "For exact work, like counting rows in a spreadsheet, it writes a small program.", "show": ["T", "T0", "T1", "T2"]},
               {"say": "It runs the code, reads the result, and uses it.", "show": ["T3", "T4", "S", "S0", "S2", "S3"]},
               {"say": "No guessing. The numbers are counted, not estimated.", "show": []}]},
    {"head": ["Phase 3", "Hand off the whole task"], "layout": "steps",
     "data": {"arrows": True, "items": [
         {"n": "YOU", "t": "Set the outcome", "b": "“Follow up with every lead who's been quiet for 5+ days.”"},
         {"n": "AGENT", "t": "Does the work", "b": "Plans, uses its tools, and checks its own results.", "accent": True},
         {"n": "YOU", "t": "Check the result", "b": "Review the drafts. Fix the instructions, not just the output."}]},
     "lines": [{"say": "Phase three. Hand off the whole task.", "show": []},
               {"say": "Give the agent the outcome you want, not step-by-step instructions.", "show": ["K0"]},
               {"say": "It plans, uses its tools, and checks its own work.", "show": ["K1"]},
               {"say": "Your job becomes checking what it produced.", "show": ["K2"]}]},
    {"head": ["Under the hood", "An agent is a loop"], "layout": "loop",
     "data": {"center": "The agent loop", "centerSub": "until the task is done",
              "labels": ["Think", "Use a tool", "Look", "Repeat"],
              "side": [{"t": "Runs in a sandbox: a closed-off workspace, unless you allow more.", "box": True}]},
     "lines": [{"say": "Under the hood, an agent is a loop.", "show": ["RING"]},
               {"say": "Think, use a tool, look at the result, and repeat, until the task is done.", "show": []},
               {"say": "The code runs in a sandbox, a closed-off workspace, unless you allow more.", "show": ["X0"]}]},
    {"head": None, "layout": "title",
     "data": {"eyebrow": "Recap", "title": "A chatbot advises. An agent acts.", "size": 104,
              "sub": "Next · Episode 2: Leave the Browser"},
     "lines": [{"say": "So remember: a chatbot advises. An agent acts.", "show": ["g0"]},
               {"say": "Next episode: leave the browser, and put an agent to work on your own computer.", "show": ["g1"],
                "cap": "Next: leave the browser and put an agent to work on your own computer."}]},
   ])

def T(eyebrow, title, sub, lines, size=124, nlines=1):
    return {"head": None, "layout": "title", "data": {"eyebrow": eyebrow, "title": title, "sub": sub, "size": size, "lines": nlines}, "lines": lines}
def S(say, show=(), cap=None, wait=0):
    d = {"say": say, "show": list(show)}
    if cap: d["cap"] = cap
    if wait: d["wait"] = wait
    return d
def EPI(n): return f"Building an AI Employee · Episode {n}"

# ---------------------------------------------------------------- Episode 2
ep(2, "Leave the Browser", TAG.format(2),
   [{"name": "Why leave", "from": 1, "to": 1}, {"name": "Pick a tool", "from": 2, "to": 2},
    {"name": "Give it a folder", "from": 3, "to": 3}, {"name": "Real task", "from": 4, "to": 4},
    {"name": "Setup tips", "from": 5, "to": 5}],
   [
    T(EPI(2), "Leave the Browser", "SpaceX paid $60 billion for an AI coding tool. Here's why that matters to you.",
      [S("Episode two. Leave the browser.", ["g0"]),
       S("In August, SpaceX completed a sixty-billion-dollar purchase of an AI coding tool called Cursor.", ["g1"],
         cap="In August 2026, SpaceX completed its $60 billion purchase of the AI coding tool Cursor."),
       S("Here's why tools like that matter, even if you never write a line of code.")]),
    {"head": ["The problem", "Why leave the browser"], "layout": "compare",
     "data": {"left": {"title": "Browser chat", "mode": "x", "items": ["Forgets everything when you close the tab", "Can't open your files", "You copy and paste every result"]},
              "right": {"title": "Local agent", "accent": True, "mode": "check", "items": ["Works inside a folder on your computer", "Reads and writes your files", "Keeps notes between sessions"]}},
     "lines": [S("A browser chat forgets everything when you close the tab.", ["L", "L0"]),
               S("It can't open your files, so you copy and paste every result.", ["L1", "L2"]),
               S("A local agent works inside a folder on your own computer.", ["R", "R0"]),
               S("It reads and writes your files, and keeps notes between sessions.", ["R1", "R2"])]},
    {"head": ["Phase 1", "Pick one tool"], "layout": "steps",
     "data": {"items": [{"n": "ANTHROPIC", "t": "Claude Code", "b": "Runs in the terminal, or inside an editor such as VS Code."},
                        {"n": "OPENAI", "t": "Codex", "b": "Runs in the terminal, in an editor, or in the cloud."},
                        {"n": "NOW OWNED BY SPACEX", "t": "Cursor", "b": "A code editor with AI built in."}],
              "note": "Pick one, and stay with it for a month."},
     "lines": [S("Phase one. Pick one tool."),
               S("Claude Code, from Anthropic, runs in the terminal, or inside an editor.", ["K0"]),
               S("Codex, from OpenAI, runs in the terminal, an editor, or the cloud.", ["K1"]),
               S("Cursor is a code editor with AI built in.", ["K2"]),
               S("Pick one, and stay with it for a month.", ["NOTE"])]},
    {"head": ["Phase 2", "Give it a folder"], "layout": "terminal",
     "data": {"lines": [["cmd", "mkdir sales-ops && cd sales-ops"], ["cmd", "claude"], ["ok", "Reading CLAUDE.md"],
                        ["ok", "Role: sales operations"], ["dim", ""], ["prompt", "ready for a task"]],
              "side": {"title": "Project folder", "rows": [{"t": "sales-ops/"}, {"t": "  CLAUDE.md", "accent": True}, {"t": "  leads.csv"}, {"t": "  outputs/"}]}},
     "lines": [S("Phase two. Give it a folder.", ["T"]),
               S("Make one folder for one job, and open the tool inside it.", ["T0", "T1"]),
               S("It reads the instruction file in that folder at the start of every session.", ["T2", "T3", "T4", "T5", "S", "S0", "S1"]),
               S("Everything it reads and writes stays there, so you can see exactly what it did.", ["S2", "S3"])]},
    {"head": ["Phase 3", "Run a real task"], "layout": "doc",
     "data": {"file": "Claude Code · sales-ops/", "lines": ["> Find leads with no reply in 5 days", "  and draft a follow-up for each.", "",
                                                         "Reading leads.csv … 214 rows", "Found 23 quiet leads", "Wrote 23 drafts to outputs/", "Done. Review them when you're ready."]},
     "lines": [S("Phase three. Run a real task, something you already do every week.", ["D"]),
               S("Type the job in one sentence: find leads with no reply in five days, and draft a follow-up for each.", ["D0", "D1"],
                 cap="Type the job in one sentence: find leads with no reply in 5 days, and draft a follow-up for each."),
               S("It reads the file, writes the drafts into an outputs folder, and tells you what it did.", ["D3", "D4", "D5", "D6"])]},
    {"head": ["Before you start", "Three setup tips"], "layout": "steps",
     "data": {"items": [{"n": "1", "t": "An account", "b": "Each tool needs an account with its maker, usually a paid plan."},
                        {"n": "2", "t": "An instruction file", "b": "CLAUDE.md or AGENTS.md: role, rules and tone, read every session."},
                        {"n": "3", "t": "A way to undo", "b": "Git, or at least a backup copy of the folder."}]},
     "lines": [S("Three setup tips."),
               S("Each tool needs an account with its maker, usually a paid plan.", ["K0"]),
               S("Add an instruction file with the role, the rules, and your tone.", ["K1"]),
               S("And keep a way to undo: Git, or at least a backup copy of the folder.", ["K2"])]},
    T("Recap", "One tool. One folder. One real task.", "Next · Episode 3: API, CLI or MCP?",
      [S("One tool, one folder, one real task. That's the whole first step.", ["g0"]),
       S("Next episode: the three ways an agent connects to your apps.", ["g1"])], size=100),
   ])

# ---------------------------------------------------------------- Episode 3
ep(3, "API, CLI or MCP?", TAG.format(3),
   [{"name": "Three doors", "from": 1, "to": 1}, {"name": "How MCP works", "from": 2, "to": 2},
    {"name": "Pick per tool", "from": 3, "to": 3}, {"name": "Read-only", "from": 4, "to": 4}, {"name": "Two rules", "from": 5, "to": 5}],
   [
    T(EPI(3), "API, CLI or MCP?", "Every app has three doors. Your AI only needs to know which one to knock on.",
      [S("Episode three. A P I, C L I, or M C P?", ["g0"], cap="Episode 3: API, CLI or MCP?"),
       S("Every app has three doors. Your AI only needs to know which one to knock on.", ["g1"])]),
    {"head": ["Phase 1", "Know the three doors"], "layout": "steps",
     "data": {"items": [{"n": "API", "t": "The loading dock", "b": "Programs swap structured requests and answers. The agent calls it with a key."},
                        {"n": "CLI", "t": "The staff entrance", "b": "Commands typed in a terminal, like gh or gcloud."},
                        {"n": "MCP", "t": "The universal adapter", "b": "The app introduces its actions. The agent calls them directly.", "accent": True}]},
     "lines": [S("Phase one. Know the three doors."),
               S("An A P I is the loading dock, where programs swap structured requests and answers.", ["K0"],
                 cap="An API is the loading dock, where programs swap structured requests and answers."),
               S("Web A P Is like this have run the internet for about twenty years.", cap="Web APIs like this have run the internet for about twenty years."),
               S("A C L I is the staff entrance: commands typed in a terminal.", ["K1"], cap="A CLI is the staff entrance: commands typed in a terminal."),
               S("And M C P is a universal adapter.", ["K2"], cap="And MCP is a universal adapter.")]},
    {"head": ["Phase 1", "How MCP works"], "layout": "steps",
     "data": {"arrows": True, "items": [{"n": "1", "t": "Connect", "b": "You add a connector, for example Gmail."},
                                        {"n": "2", "t": "It introduces itself", "b": "“I can search, read, label and draft emails.”", "accent": True},
                                        {"n": "3", "t": "The agent decides", "b": "It calls those actions when a task needs them."}]},
     "lines": [S("People say that with M C P, the tool talks first.", ["K0"], cap="People say that with MCP, “the tool talks first.”"),
               S("It means the app describes its own actions to the AI, so nobody writes custom connection code.", ["K1"]),
               S("The agent still decides when to use them.", ["K2"])]},
    {"head": ["Phase 2", "Pick the door per tool"], "layout": "table",
     "data": {"cols": ["If…", "Use"], "widths": [3, 1], "y": 60,
              "rows": [["The app has a connector", "MCP"], ["It's a technical tool with its own command line", "CLI"], ["Neither exists", "The raw API"]]},
     "lines": [S("Phase two. Pick the door per tool.", ["H"]),
               S("If the app has a connector, use M C P.", ["R0"], cap="If the app has a connector, use MCP."),
               S("For technical tools that come with a command line, use the C L I.", ["R1"], cap="For technical tools that come with a command line, use the CLI."),
               S("And when neither exists, fall back to the raw A P I.", ["R2"], cap="When neither exists, fall back to the raw API.")]},
    {"head": ["Phase 3", "Connect read-only first"], "layout": "hub",
     "data": {"center": "Agent", "centerSub": "SALES OPS",
              "nodes": [{"label": "Gmail", "edge": "MCP"}, {"label": "Calendar", "edge": "MCP"}, {"label": "CRM", "edge": "API"}, {"label": "Drive", "edge": "MCP"}]},
     "lines": [S("Phase three. Connect read-only first.", ["C"]),
               S("For our sales-ops assistant, Gmail and the calendar connect through M C P.", ["N0", "N1"], cap="For our sales-ops assistant, Gmail and the calendar connect through MCP."),
               S("The C R M has no connector, so it uses the A P I, with a read-only key.", ["N2"], cap="The CRM has no connector, so it uses the API, with a read-only key."),
               S("Now it can check the calendar for free slots, and draft follow-ups that offer two meeting times.", ["N3"]),
               S("Sending and deleting come later, after the safety rules in episode seven.")]},
    {"head": ["Before you connect", "Two rules"], "layout": "steps",
     "data": {"items": [{"n": "1", "t": "Trust the source", "b": "Every connector acts with your account's permissions."},
                        {"n": "2", "t": "Hide your keys", "b": "API keys go in a settings file the agent reads, never pasted into chat."}]},
     "lines": [S("Two rules before you connect anything."),
               S("Every connector acts with your account's permissions, so install only from sources you trust.", ["K0"]),
               S("And keep A P I keys in a settings file, never pasted into chat.", ["K1"], cap="And keep API keys in a settings file, never pasted into chat.")]},
    T("Recap", "Connector first. Command line second. API last.", "Next · Episode 4: Teach It Your Business",
      [S("Connector first, command line second, A P I last.", ["g0"], cap="Connector first. Command line second. API last."),
       S("Next episode: how to teach your agent about your business.", ["g1"])], size=96, nlines=2),
   ])

# ---------------------------------------------------------------- Episode 4
ep(4, "Teach It Your Business", TAG.format(4),
   [{"name": "Four methods", "from": 1, "to": 1}, {"name": "Core facts", "from": 2, "to": 2},
    {"name": "Reference files", "from": 3, "to": 3}, {"name": "RAG", "from": 4, "to": 4}, {"name": "Common mistake", "from": 5, "to": 5}],
   [
    T(EPI(4), "Teach It Your Business", "Your AI is smart, but it has never heard of your company.",
      [S("Episode four. Teach it your business.", ["g0"]),
       S("Your AI is smart, but it has never heard of your company.", ["g1"]),
       S("Here are four ways to fix that. Most businesses only need the first two.")]),
    {"head": ["The four methods", "Climb only as high as you need"], "layout": "ladder",
     "data": {"rungs": [{"t": "Instruction file", "note": "Facts needed on every task · minutes"},
                        {"t": "Files in the folder", "note": "A few hundred documents · minutes"},
                        {"t": "Connected drive", "note": "Live documents that change · an hour"},
                        {"t": "RAG", "note": "Thousands of documents · days, plus upkeep"}]},
     "lines": [S("Think of it as a ladder. First, the instruction file, for facts needed on every task.", ["U0"]),
               S("Then files in the project folder, for a few hundred documents.", ["U1"]),
               S("A connected drive, for live documents that change.", ["U2"]),
               S("And RAG, for thousands of documents.", ["U3"], cap="And RAG (retrieval-augmented generation), for thousands of documents."),
               S("Climb only as high as you need.")]},
    {"head": ["Phase 1", "Write the core facts down once"], "layout": "doc",
     "data": {"file": "sales-ops/CLAUDE.md", "lines": ["# Company", "Example Co. · B2B IT services", "# Services and prices", "Health check $1,500 · Audit $4,000",
                                                     "# Tone", "Short, warm, no jargon"]},
     "lines": [S("Phase one. Write the facts it always needs down, once.", ["D", "D0", "D1"]),
               S("Who you are, what you sell, your prices, and your tone.", ["D2", "D3", "D4", "D5"]),
               S("They go in the instruction file, which the agent reads every session.")]},
    {"head": ["Phase 2", "Put reference files in reach"], "layout": "steps",
     "data": {"arrows": True, "items": [{"n": "1", "t": "A task arrives", "b": "“Draft a follow-up for Acme.”"},
                                        {"n": "2", "t": "It searches the folder", "b": "Finds reference/acme-proposal.pdf"},
                                        {"n": "3", "t": "Opens only what it needs", "b": "Quotes the right package in the draft.", "accent": True}]},
     "lines": [S("Phase two. Put reference files within reach."),
               S("Price lists, past proposals, and the brand guide go in the project folder, or a connected drive."),
               S("When a task arrives, the agent searches them,", ["K0", "K1"]),
               S("and opens only the files it actually needs.", ["K2"])]},
    {"head": ["Phase 3", "Use RAG only for big libraries"], "layout": "steps",
     "data": {"arrows": True, "items": [{"n": "1", "t": "Split", "b": "Thousands of documents become small passages."},
                                        {"n": "2", "t": "Index by meaning", "b": "Passages with similar ideas are stored together."},
                                        {"n": "3", "t": "Retrieve", "b": "The agent gets only the closest matches."}],
              "note": "Worth it for years of support tickets. Overkill for a price list."},
     "lines": [S("Phase three. Use RAG only for big libraries.", cap="Phase 3: use RAG only for big libraries."),
               S("RAG splits thousands of documents into small passages,", ["K0"]),
               S("indexes them by meaning,", ["K1"]),
               S("and hands the agent only the closest matches.", ["K2"]),
               S("It's worth building for years of support tickets. For a price list, it's overkill.", ["NOTE"])]},
    {"head": ["Common mistake", "Don't over-build"], "layout": "compare",
     "data": {"left": {"title": "Over-built", "mode": "x", "items": ["A RAG system for 40 files", "Days of setup", "Upkeep every time a file changes"]},
              "right": {"title": "Right-sized", "accent": True, "mode": "check", "items": ["One instruction file", "A tidy reference folder", "Running in an afternoon"]}},
     "lines": [S("The most common real mistake is building RAG when a well-organized folder would do.", ["L", "L0", "L1", "L2"]),
               S("Start with an instruction file and a tidy folder. Most businesses never need more.", ["R", "R0", "R1", "R2"])]},
    T("Recap", "Start with a file and a folder.", "Next · Episode 5: Skills and Sub-Agents",
      [S("Start with a file and a folder. Climb the ladder only when you have to.", ["g0"]),
       S("Next episode: skills and sub-agents.", ["g1"])], size=100),
   ])

# ---------------------------------------------------------------- Episode 5
ep(5, "Skills and Sub-Agents", TAG.format(5),
   [{"name": "Save a skill", "from": 1, "to": 1}, {"name": "Auto-trigger", "from": 2, "to": 2},
    {"name": "Sub-agents", "from": 3, "to": 3}, {"name": "Example", "from": 4, "to": 4}, {"name": "Good to know", "from": 5, "to": 5}],
   [
    T(EPI(5), "Skills and Sub-Agents", "If you've explained the same task to your AI twice, you're doing it wrong.",
      [S("Episode five. Skills and sub-agents.", ["g0"]),
       S("If you've explained the same task to your AI twice, you're doing it wrong.", ["g1"])]),
    {"head": ["Phase 1", "Turn a repeated task into a skill"], "layout": "doc",
     "data": {"file": "skills/follow-up-email/SKILL.md", "input": "Do today's follow-ups",
              "lines": ['When: "Do today\'s follow-ups"', "1. Find leads quiet for 5+ days", "2. Read the thread + CRM notes",
                        "3. Draft in house tone", "4. Queue drafts for approval"]},
     "lines": [S("Phase one. Turn a repeated task into a skill.", ["D"]),
               S("A skill is a saved how-to guide, plus the tools it needs.", ["D0"]),
               S("Do the task well once with the agent, then ask it to write that session up as a skill.", ["D1", "D2", "D3", "D4"])]},
    {"head": ["Phase 2", "Let the skill trigger itself"], "layout": "steps",
     "data": {"arrows": True, "items": [{"n": "YOU", "t": "Ask in one sentence", "b": "“Do today's follow-ups.”"},
                                        {"n": "AGENT", "t": "Matches the skill", "b": "The skill's first line says when to use it.", "accent": True},
                                        {"n": "AGENT", "t": "Follows the steps", "b": "The same way, every time."}]},
     "lines": [S("Phase two. Let the skill trigger itself."),
               S("You ask in one sentence.", ["K0"]),
               S("The agent matches it to the skill's first line, which says when to use it.", ["K1"]),
               S("Then it follows the steps, the same way every time. You stop re-explaining.", ["K2"])]},
    {"head": ["Phase 3", "Send side-jobs to sub-agents"], "layout": "hub",
     "data": {"center": "Lead agent", "nodes": [{"label": "Research · Acme", "edge": "brief"}, {"label": "Research · Nordline", "edge": "brief"},
                                                {"label": "Research · Sahel Co", "edge": "brief"}, {"label": "Review drafts", "edge": "check"}]},
     "lines": [S("Phase three. Send side-jobs to sub-agents.", ["C"]),
               S("A sub-agent is a helper with its own clean workspace.", ["N0"]),
               S("It does one job, like researching a lead, and reports back a short answer.", ["N1", "N2"]),
               S("One can even review the drafts with fresh eyes. The main conversation stays clear for the big picture.", ["N3"])]},
    {"head": ["Sales-ops example", "A skill plus sub-agents"], "layout": "steps",
     "data": {"arrows": True, "items": [{"n": "1", "t": "Skill runs", "b": "follow-up-email finds 3 quiet leads."},
                                        {"n": "2", "t": "Sub-agents research", "b": "One per lead: the latest company news."},
                                        {"n": "3", "t": "Two lines back", "b": "“Acme just opened a Dubai office.”"},
                                        {"n": "4", "t": "Personal drafts", "b": "The lead agent writes each follow-up.", "accent": True}]},
     "lines": [S("In our sales-ops example, the follow-up skill finds three quiet leads.", ["K0"]),
               S("It sends one sub-agent per lead to research the company's latest news.", ["K1"]),
               S("Each one returns two lines,", ["K2"]),
               S("and the main agent uses them to personalize every draft.", ["K3"])]},
    {"head": ["Good to know", "What a skill is, and when not to delegate"], "layout": "steps",
     "data": {"items": [{"n": "SKILL", "t": "It's just a folder", "b": "A SKILL.md file: a name, “use this when…”, the steps, plus any templates or scripts."},
                        {"n": "SUB-AGENTS", "t": "They cost time", "b": "Use them for big, parallel or second-opinion work, not one-line tasks."}]},
     "lines": [S("Two things to know."),
               S("A skill is just a folder with a skill file: a name, when to use it, the steps, and any templates.", ["K0"],
                 cap="A skill is just a folder with a SKILL.md file: a name, when to use it, the steps, and any templates."),
               S("And sub-agents cost time and usage, so save them for big, parallel, or second-opinion work.", ["K1"])]},
    T("Recap", "Explain it once. Delegate the side-jobs.", "Next · Episode 6: Give It a Goal, Not a Prompt",
      [S("Explain it once. Delegate the side-jobs.", ["g0"]),
       S("Next episode: give it a goal, not a prompt.", ["g1"])], size=96, nlines=2),
   ])

# ---------------------------------------------------------------- Episode 6
ep(6, "Give It a Goal, Not a Prompt", TAG.format(6),
   [{"name": "Finish line", "from": 1, "to": 1}, {"name": "The loop", "from": 2, "to": 2},
    {"name": "Schedule", "from": 3, "to": 3}, {"name": "Reality check", "from": 4, "to": 4}],
   [
    T(EPI(6), "Give It a Goal, Not a Prompt", "Stop typing the next step. Give it the finish line.",
      [S("Episode six. Give it a goal, not a prompt.", ["g0"]),
       S("Stop typing the next step. Give it the finish line.", ["g1"])], size=104),
    {"head": ["Phase 1", "Write a goal with a finish line"], "layout": "table",
     "data": {"cols": ["Prompt-style", "Goal-style"], "widths": [2, 3], "y": 40,
              "rows": [["“Help with my leads”", "“For every lead quiet 30+ days, draft a follow-up and log it. Stop when none are left.”"],
                       ["“Look at the pipeline”", "“List deals with no activity in 14 days, with owner and last contact date.”"]]},
     "lines": [S("Phase one. Write a goal with a finish line.", ["H"]),
               S("Help with my leads is a prompt. The agent can't tell when it's done.", cap="“Help with my leads” is a prompt. The agent can't tell when it's done."),
               S("For every lead quiet thirty days or more, draft a follow-up, and stop when none are left. That's a goal.", ["R0"],
                 cap="“For every lead quiet 30+ days, draft a follow-up, stop when none are left.” That's a goal."),
               S("Name the result, and how you'll know it's finished.", ["R1"])]},
    {"head": ["Phase 2", "Let the loop run"], "layout": "loop",
     "data": {"center": "Goal", "centerSub": "every quiet lead handled", "labels": ["Plan", "Act", "Check", "Decide"],
              "side": [{"t": "It stops early only for something it must ask you about.", "box": True}]},
     "lines": [S("Phase two. Let the loop run.", ["RING"]),
               S("The agent plans, acts, checks the result, and decides the next step,"),
               S("over and over, until the finish line is met."),
               S("It only stops early for something it must ask you about.", ["X0"])]},
    {"head": ["Phase 3", "Schedule it, and leave a trail"], "layout": "loop",
     "data": {"center": "Goal", "centerSub": "runs again each morning", "labels": ["Plan", "Act", "Check", "Decide"], "clock": "Every weekday · 08:00", "sideGap": 100,
              "side": [{"t": "Morning summary", "big": True}, {"t": "12 leads checked"}, {"t": "7 drafts waiting for approval"}, {"t": "Full log in outputs/run-log.md", "muted": True}]},
     "lines": [S("Phase three. Put it on a schedule, and leave a trail.", ["CLK", "RING"]),
               S("Every weekday at eight, the same goal runs again."),
               S("The agent keeps a task list and a log, so you can see progress when you come back.", ["X3"]),
               S("Your morning summary: twelve leads checked, seven drafts waiting for approval.", ["X0", "X1", "X2"],
                 cap="Your morning summary: 12 leads checked, 7 drafts waiting for approval.")]},
    {"head": ["Reality check", "How long it really runs"], "layout": "steps",
     "data": {"items": [{"n": "THE CLAIM", "t": "“Works non-stop for days”", "b": "A best case, not typical."},
                        {"n": "TYPICAL", "t": "Minutes to hours", "b": "Or a short run on a schedule.", "accent": True},
                        {"n": "SAFETY NET", "t": "Limits and a stop rule", "b": "“After 3 failed attempts, stop and report.”"}]},
     "lines": [S("You'll hear that agents work non-stop for days. That's a best case.", ["K0"]),
               S("Most business loops run for minutes to hours, or on a schedule.", ["K1"]),
               S("So set a time limit, and a rule for when it's stuck: after three failed attempts, stop and report.", ["K2"],
                 cap="So set a time limit, and a rule for when it's stuck: after 3 failed attempts, stop and report.")]},
    T("Recap", "Name the finish line. Then let it run.", "Next · Episode 7: Safety Hooks",
      [S("Name the finish line, then let it run.", ["g0"]),
       S("Next episode: safety hooks, so it asks before doing anything risky.", ["g1"])], size=96, nlines=2),
   ])

# ---------------------------------------------------------------- Episode 7
ep(7, "Safety Hooks", TAG.format(7),
   [{"name": "Three lists", "from": 1, "to": 1}, {"name": "Rules and hooks", "from": 2, "to": 2},
    {"name": "Approvals", "from": 3, "to": 3}, {"name": "Two habits", "from": 4, "to": 4}],
   [
    T(EPI(7), "Safety Hooks", "Your AI can delete a folder faster than you can say “wait.”",
      [S("Episode seven. Safety hooks.", ["g0"]),
       S("Your AI can delete a folder faster than you can say wait. Don't trust luck.", ["g1"],
         cap="Your AI can delete a folder faster than you can say “wait.” Don't trust luck.")]),
    {"head": ["Phase 1", "Sort actions into three lists"], "layout": "table",
     "data": {"cols": ["Always fine", "Ask me first", "Never"], "y": 40,
              "rows": [["Read files and records", "Send any email or message", "Delete outside the project"],
                       ["Draft into outputs/", "Change CRM records", "Touch payment settings"],
                       ["Search the web", "Overwrite an existing file", "Share files publicly"]]},
     "lines": [S("Phase one. Sort every action into three lists.", ["H"]),
               S("Reading is always fine. Sending a message: ask me first. Deleting outside the project: never.", ["R0"]),
               S("Drafting is fine. Changing C R M records: ask first. Payment settings: never.", ["R1"],
                 cap="Drafting is fine. Changing CRM records: ask first. Payment settings: never."),
               S("Searching is fine. Overwriting a file: ask first. Sharing publicly: never.", ["R2"])]},
    {"head": ["Phase 2", "Set the rules in the tool"], "layout": "steps",
     "data": {"arrows": True, "items": [{"n": "PERMISSIONS", "t": "Allow · Ask · Deny", "b": "Your three lists, turned into rules."},
                                        {"n": "HOOK", "t": "Runs before the action", "b": "A small script that can block it, or ask you first.", "accent": True},
                                        {"n": "IN CLAUDE CODE", "t": "PreToolUse", "b": "The event that fires right before a tool runs."}]},
     "lines": [S("Phase two. Set the rules in the tool."),
               S("Permission settings turn your three lists into allow, ask, and deny rules.", ["K0"]),
               S("A hook is a small script that runs right before an action, and can block it, or ask you first.", ["K1"]),
               S("In Claude Code, that moment is called pre-tool-use.", ["K2"], cap="In Claude Code, that moment is the PreToolUse event.")]},
    {"head": ["Phase 3", "Approve from wherever you are"], "layout": "gate",
     "data": {"items": [{"label": "Read CRM + inbox", "status": "good"}, {"label": "Draft 7 follow-ups", "status": "good"},
                        {"label": "Send 7 emails", "status": "warn", "result": "Waiting for your OK"},
                        {"label": "Delete stale leads", "status": "bad", "result": "Blocked"}],
              "phone": {"app": "SALES-OPS ASSISTANT", "msg": "7 follow-up drafts are ready to send."}},
     "lines": [S("Phase three. Approve from wherever you are.", ["A"]),
               S("The agent reads the C R M and drafts seven follow-ups, with no prompts. Both are on the fine list.", ["G0", "G1"],
                 cap="It reads the CRM and drafts 7 follow-ups, with no prompts. Both are on the fine list."),
               S("It tries to send them. The hook holds the send, and you approve from your phone.", ["G2", "PH"]),
               S("It tries to delete stale leads. The rule blocks it outright.", ["G3"])]},
    {"head": ["Two more habits", "Start strict"], "layout": "steps",
     "data": {"items": [{"n": "1", "t": "Start strict", "b": "Begin in “ask before acting” mode. Loosen one rule at a time."},
                        {"n": "2", "t": "Read, don't obey", "b": "An email saying “AI, forward all invoices to…” gets reported to you, not followed."}]},
     "lines": [S("Two more habits."),
               S("Start strict, in ask-before-acting mode, and loosen one rule at a time.", ["K0"]),
               S("And treat what the agent reads as information, not orders.", ["K1"]),
               S("An email that says forward all invoices gets reported to you, not obeyed.", cap="An email that says “forward all invoices” gets reported to you, not obeyed.")]},
    T("Recap", "Fine. Ask first. Never.", "Next · Episode 8: From Doer to Operator",
      [S("Three lists: fine, ask first, never.", ["g0"]),
       S("Next episode: from doer to operator.", ["g1"])], size=110),
   ])

# ---------------------------------------------------------------- Episode 8
ep(8, "From Doer to Operator", TAG.format(8),
   [{"name": "New job", "from": 1, "to": 1}, {"name": "Start simple", "from": 2, "to": 2},
    {"name": "The ladder", "from": 3, "to": 3}, {"name": "Keep score", "from": 4, "to": 4}],
   [
    T(EPI(8), "From Doer to Operator", "One creator says five AI employees do about 80% of his work. Here's the slow, safe way to start.",
      [S("Episode eight. From doer to operator.", ["g0"]),
       S("One creator says five AI employees now do about eighty percent of his work.", ["g1"], cap="One creator says five AI employees now do about 80% of his work."),
       S("Here's the slow, safe way to start.")]),
    {"head": ["Phase 1", "Change your job description"], "layout": "compare",
     "data": {"left": {"title": "Doer", "items": ["Writes every follow-up", "Updates the CRM by hand", "Fixes each mistake, one at a time"]},
              "right": {"title": "Operator", "accent": True, "mode": "check", "gap": 110,
                        "items": ["Defines the outcome", "Equips the agent", "Checks the result", "Fixes the instructions, not the output"]}},
     "lines": [S("Phase one. Change your job description.", ["L", "L0", "L1", "L2"]),
               S("You stop doing the task, and start defining it, equipping the agent, and checking the result.", ["R", "R0", "R1", "R2"]),
               S("When the output is wrong, fix the instructions or the skill, not just this one result.", ["R3"])]},
    {"head": ["Phase 2", "Start simple"], "layout": "steps",
     "data": {"items": [{"n": "1", "t": "Weekly or more?", "b": "Frequent tasks pay back fastest."},
                        {"n": "2", "t": "Follows rules?", "b": "Clear steps, few judgment calls."},
                        {"n": "3", "t": "Mistakes cheap?", "b": "A wrong draft costs minutes, not a client."},
                        {"n": "4", "t": "Easy to check?", "b": "You can verify it at a glance."}],
              "note": "Hand over the two highest-scoring tasks first."},
     "lines": [S("Phase two. Start with simple, frequent, low-risk tasks."),
               S("Score each task with four questions. Is it done weekly or more? Does it follow rules?", ["K0", "K1"]),
               S("Is a mistake cheap? Is the result easy to check?", ["K2", "K3"]),
               S("Start with the top two.", ["NOTE"])]},
    {"head": ["Phase 3", "Climb one rung at a time"], "layout": "ladder",
     "data": {"rungs": [{"t": "Assist", "note": "Week 1: drafts follow-ups when asked"}, {"t": "Routine task"},
                        {"t": "Scheduled task", "note": "Month 1: runs every weekday morning"}, {"t": "Multi-step process"},
                        {"t": "End-to-end ownership", "note": "Month 3: runs it all, flags exceptions"}],
              "meter": {"label": "Routine work handed over", "to": 0.8, "dur": 10}},
     "lines": [S("Phase three. Climb one rung at a time.", ["U0"]),
               S("Assist, then a routine task, then a scheduled task,", ["U1", "U2"]),
               S("then a multi-step process, and finally end-to-end ownership.", ["U3", "U4"]),
               S("Each rung should run cleanly for two to four weeks before you add the next.")]},
    {"head": ["Keep score", "Two numbers per task"], "layout": "steps",
     "data": {"items": [{"n": "1", "t": "Hours handed over", "b": "Per week, per task."}, {"n": "2", "t": "Errors caught in review", "b": "They tell you what's ready to scale."}],
              "note": "About that 80%: it's one creator's report on his own businesses, for routine work, not a whole job."},
     "lines": [S("Keep score with two numbers per task: hours handed over each week, and errors caught in review.", ["K0", "K1"]),
               S("And about that eighty percent. It's one creator's report on his own businesses, and it's about routine work, not a whole job.", ["NOTE"],
                 cap="About that 80%: it's one creator's report on his own businesses, for routine work, not a whole job.")]},
    T("Recap", "Define it. Equip it. Check it.", "Next · Episode 9: The 7-Stop Roadmap",
      [S("Define it, equip it, check it.", ["g0"]),
       S("Next episode: the seven-stop roadmap.", ["g1"], cap="Next episode: the 7-stop roadmap.")], size=110),
   ])

# ---------------------------------------------------------------- Episode 9
ep(9, "The 7-Stop Roadmap", TAG.format(9),
   [{"name": "The map", "from": 1, "to": 1}, {"name": "Pace", "from": 2, "to": 2}, {"name": "Traps", "from": 3, "to": 3}],
   [
    T(EPI(9), "The 7-Stop Roadmap", "New AI tools come out every week. You don't need them. You need seven stops.",
      [S("Episode nine. The seven-stop roadmap.", ["g0"], cap="Episode 9: The 7-Stop Roadmap."),
       S("New AI tools come out every week. You don't need them. You need seven stops.", ["g1"])]),
    {"head": ["The roadmap", "Seven stops, in order"], "layout": "metro",
     "data": {"stations": [{"t": "Chatbot vs. agent", "b": "List 5 weekly tasks"}, {"t": "A local agent", "b": "Folder + first task"},
                           {"t": "Instruction file", "b": "One page of rules"}, {"t": "Connect tools", "b": "Read-only email, calendar"},
                           {"t": "Skills", "b": "Your first saved routine"}, {"t": "Safety rules", "b": "Allow · ask · deny"},
                           {"t": "Goals + schedules", "b": "One task every weekday"}]},
     "lines": [S("Here's the map, built from this series.", ["LINE"]),
               S("Stop one: chatbot versus agent. Make a list of five weekly tasks.", ["P0"]),
               S("Stop two: a local agent, with a folder and your first real task.", ["P1"]),
               S("Stop three: the instruction file.", ["P2"]),
               S("Stop four: connect your tools, read-only.", ["P3"]),
               S("Stop five: your first skill.", ["P4"]),
               S("Stop six: safety rules.", ["P5"]),
               S("Stop seven: goals and schedules, with one task running every weekday.", ["P6"])]},
    {"head": ["Pace", "How long each stop takes"], "layout": "table",
     "data": {"cols": ["Stop", "Build that day", "Rough time"], "widths": [3, 4, 2], "y": 0,
              "rows": [["1 · Chatbot vs. agent", "List 5 weekly tasks", "1 hour"], ["2 · A local agent", "Folder + first real task", "1 day"],
                       ["3 · Instruction file", "Role, rules and tone", "1 hour"], ["4 · Connect tools", "Read-only email, calendar, drive", "1 day"],
                       ["5 · Skills", "Your first saved routine", "1 day"], ["6 · Safety rules", "Allow, ask, deny + one hook", "Half a day"],
                       ["7 · Goals + schedules", "One task every weekday", "1 week"]]},
     "lines": [S("How long does it take?", ["H"]),
               S("Most stops take an hour to a day, and each one ends with something running.", ["R0", "R1", "R2", "R3", "R4", "R5"]),
               S("The last one takes about a week, because you watch it run on a schedule.", ["R6"]),
               S("About two weeks, start to finish.")]},
    {"head": ["Traps to avoid", "Three ways people stall"], "layout": "steps",
     "data": {"items": [{"n": "1", "t": "Tool chasing", "b": "A new app every week means starting over every week."},
                        {"n": "2", "t": "Skipping stops", "b": "Loops before safety rules give you fast, confident mistakes."},
                        {"n": "3", "t": "Watching, not building", "b": "Every stop ends with something running on your own work."}]},
     "lines": [S("Three traps to avoid."),
               S("Tool chasing. A new app every week means starting over every week. Learn the concepts; they carry across tools.", ["K0"]),
               S("Skipping stops. Loops before safety rules give you fast, confident mistakes.", ["K1"]),
               S("And watching instead of building. Every stop should end with something running on your own work.", ["K2"])]},
    T("Series finale", "Seven stops. One AI employee.", "The sales-ops assistant in this series is this roadmap, done once, start to finish.",
      [S("Seven stops. One AI employee.", ["g0"]),
       S("The sales-ops assistant you followed in this series is this roadmap, done once, start to finish.", ["g1"]),
       S("Pick your first task this week, and start at stop one.")], size=110),
   ])
